name: Test Web
on:
  push:
  pull_request:
env:
  FORCE_COLOR: 2
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build&Test
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 6

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: pnpm
          registry-url: https://registry.npmmirror.com/

      - name: Install dependencies
        run: cd hearu_webapp && pnpm i

      - name: Run lint
        run:  cd hearu_webapp && pnpm lint && pnpm check

      - name: Build
        run:  cd hearu_webapp && pnpm build
